name: 'Changelog from PR files'
description: 'Creates a changelog and updates version name according local PR files'
inputs:
  git-token:
    description: 'Token to read PR files'
    required: true
  current-version:
    description: 'The name of the current version, before changes'
    required: false
    default: '0.0.0'
outputs:
  changelog:
    description: 'The generated changelog'
  version:
    description: 'The calculated new version'
runs:
  using: 'node16'
  main: 'index.js'
