name: 'Changelog from PRs'
description: 'Creates a changelog from merged PRs between the latest release and current branch'
inputs:
  git-token:
    description: 'GitHub token to access the API'
    required: true
  current-version:
    description: 'The name of the current version, before changes'
    required: false
    default: '0.0.0'
  label-teams:
    description: 'A list of label names that will be used as teams in the changelog'
    required: false
outputs:
  changelog:
    description: 'The generated changelog'
  version:
    description: 'The calculated new version'
runs:
  using: 'node16'
  main: 'index.js'
